Fixed translate bug for articles translation.
sawaliram/sawaliram pull request #377
Opened 2021-05-22 08:31 UTC by abhiprojectz

**Bug**:
`Translate content` gives server error 500 when translating for articles.

**Description:**
This fixes the above bug on `/dashboard/translate/answers` page.

2021-05-22 15:12 UTC, badrihippo requested changes
This works, logically speaking, but better not to make such changes in the base views because over time it'll lead to spaghetti code (one code trying to account for too many cases, like what's happened to the Search page right now).

We already have separate functions to account for two different cases (`CreateArticleTranslation` for articles and `CreateAnswerTranslation` for answers). So instead of putting the `if` condition here, you should create a `get_form` function under `CreateAnswerTranslation` which inherits from the parent one; something like

```
class CreateAnswerTranslation(BaseStartTranslation):
    ...

    def get_form(self):
        form = super().get_form()

        available_languages = self.answer.list_available_languages()

        unavailable_languages = []
        ...
```

Then in the `BaseStartTranslation` use `self.source` instead of `self.answer`. The reason is that `source` is the *normal* way to use a translation; answers are a *special case* where you get the language from the answer instead of the `source` (question).

The reason I'm suggesting all this is that, when someone looks at the code later, they can easily read `BaseStartTranslation` to see what it does, and then they can see that `CreateAnswerTranslation` is customising it in some way (getting the language list from the answer instead of the question). This is easier to understand than having to understand one large code that accounts for all the cases. It may seem like a bit more work right now, but in the long run it makes the code much easier to maintain.

Actually even the current case is a good example. Somebody tried to customise `BaseStartTranslation` directly for answers, but that ended up affecting the other translation views because it was looking for `answers` instead of looking for `source`. If they had customised `CreateAnswerTranslation` instead of `BaseStartTranslation` this bug would never have come up (or at least it would have been very easy to track down). By the way, I don't know who changed that line; it could have even been me, but whoever did it that wasn't a good idea!

Hope that was clear; let me know if you have any doubts or questions 🙂

2021-05-22 15:16 UTC, badrihippo commented
@abhiprojectz just to clarify, what you did was not *wrong*: it did solve the problem at hand. But design-wise, since this is such a large project, there are better ways to implement the solution that will work out better in the long run!

2021-05-23 17:37 UTC, pskeshu commented on dashboard/views.py
> +        # check whether its article
typo

2021-05-23 17:45 UTC, pskeshu commented
>If they had customised CreateAnswerTranslation instead of BaseStartTranslation this bug would never have come up (

Is this a larger problem with the library API?

2021-05-24 04:23 UTC, abhiprojectz commented
@badrihippo  @pskeshu   please suggest a better way to implement the above change in templates like in `translation/base_edit.html`  template 
```
...
 <select id="lang_from" name="lang_from" class="input-plain text-center">
          {% for value, label in object.source.list_available_languages %}
          <option value="{{ value }}"{% if value == object.source.tr_language %} selected{% endif %}>{{ label }}</option>
          {% endfor %}
        </select>
...
```

![hghgg](https://user-images.githubusercontent.com/64596494/119295977-bb082200-bc75-11eb-93ff-4ffbc1a543c3.PNG)

the languages filter (lang_from,lang_to) are being set from source (object) language on `translation interface` and same is used for both articles and answers (resources or research etc) so without making changes in `translation/base_edit.html`   template and without using `{% if/else %}` ,
how to extend this change to `answer_edit` and `article_edit`  template such that `base_edit` have some common fields after the `lang filters`.

2021-05-26 11:08 UTC, badrihippo commented
> > If they had customised CreateAnswerTranslation instead of BaseStartTranslation this bug would never have come up (
> 
> Is this a larger problem with the library API? @badrihippo

@pskeshu not a *problem* per se, but a usage pattern that needs to be encouraged. Perhaps it needs to be documented a bit better; on the other hand once 2-3 exceptions like this are added the recommended structure will hopefully become more apparent to new programmers

2021-05-26 11:18 UTC, badrihippo commented
@abhiprojectz two possible options; choose whichever you're more comfortable with.

### Option 1: Template-level override

You can create a new `{% block %}` like `{% block language_selector %}`. The `base_edit.html` can have the default value, i.e.

```
        ...
        {% block language_selector %}
        <select id="lang_from" name="lang_from" class="input-plain text-center">
          {% for value, label in object.source.list_available_languages %}
          <option value="{{ value }}"{% if value == object.source.tr_language %} selected{% endif %}>{{ label }}</option>
          {% endfor %}
        </select>
        {% block language_selector %}
        ...
```

The no change will be necessary in `article_edit.htm`, but in `answer_edit` you can override by putting a different `{% block language-selector %}` there, similarly to how it is done for `{% block title %}`, etc. in other places.

### Option 2: View-level override

Alternatively, you can set a new context variable called `available_languages` in `EditAnswerTranslation` in `views.py`. Then in `base.html` you can change the line to `{% for value, label in available_languages or object.source.list_available_languages %}` (we are keeping the `or` so people don't have to manually compute the `available_languages` when sticking with the default option).

2021-05-26 12:21 UTC, abhiprojectz commented
Thanks @badrihippo  ,made the changes.

2021-05-26 14:27 UTC, badrihippo approved these changes
Looking good!

2021-05-26 15:37 UTC, merged