Language Selectors modified
sawaliram/sawaliram pull request #403
Opened 2021-06-12 03:56 UTC by abhiprojectz

fixes: [#369](https://github.com/sawaliram/sawaliram/issues/369)

2021-06-12 13:52 UTC, Sshashank18 requested changes
I am getting this view. 

![Screenshot from 2021-06-12 19-21-27](https://user-images.githubusercontent.com/46228280/121778179-6c361400-cbb3-11eb-92e7-88e768666f27.png)

2021-06-13 02:30 UTC, abhiprojectz commented
@Sshashank18  make sure, whether have you synced your master and if yes then pull this PR from master branch, then checkout to this Pull, as this issue is already fixed by [#392 ](https://github.com/sawaliram/sawaliram/pull/392)

2021-06-14 12:14 UTC, Sshashank18 approved these changes
Okay. Working fine on my localhost.

2021-06-17 17:32 UTC, subindevs approved these changes

2021-06-18 05:06 UTC, ukey54 approved these changes

2021-06-18 05:13 UTC, merged